### ISSUE TITLE
集成之后会报找不到springboot的一些依赖包

### ISSUE THREAD

**Issue by imooni** [yueshutong/Spring-Project-Tree#1]
![image](https://user-images.githubusercontent.com/20927567/52338211-b5ef1c80-2a44-11e9-8cc5-4f54974df57a.png)

**Comment by imooni** [comment]
是需要在spring  (非springboot)  项目中添加缺少的依赖吗?还是直接在mvn install 生成的jar包里面直接包括。

**Comment by imooni** [comment]
解决了，是必须以依赖方式引入不能直接添加jar包到项目下。还有如果使用spring方式要注意版本冲突问题，spring版本不要超过5。

**Comment by onblog** [comment]
解决了就好，可以看下最新版本的。
