### ISSUE TITLE
页面第一次显示不完整

### ISSUE THREAD

**Issue by ruanwenjun** [yueshutong/Spring-Project-Tree#3]
加上注解，本地启动项目正常启动。
访问http://localhost:8080/projecttree ， 页面显示spring project tree , 但是无其他内容。
访问一次controller之后，页面才显示调用访问。
能否在项目启动之后，页面显示所有切点表达式匹配的方法调用依赖情况。

**Comment by onblog** [comment]
我也在想如何解决这个问题？？？
